# Support Vector Machine

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib as mpl
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn import svm

In [2]:
iris = load_iris()
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [3]:
iris['DESCR']

'.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ============== ==== =

In [4]:
data = pd.DataFrame(iris['data'], columns = ['petal length', 'petal width', 'sepal length', 'sepal width'])
data['species'] = iris['target']
data['species'] = data['species'].apply(lambda x: iris['target_names'][x])
data

petal length  petal width  sepal length  sepal width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [5]:
X = iris.data[:, :2] # I take petal features
Y = iris.target
C_Regularization = 0.5 # SVM regularization parameter

In [6]:
trainX, testX, trainY, testY = train_test_split(X, Y, random_state = 1, test_size = 0.4)

In [7]:
def classifier():
    classify = svm.SVC(C_Regularization, kernel = 'linear', decision_function_shape = 'ovr')
    return classify

In [8]:
classifier = classifier()
classifier

SVC(C=0.5, kernel='linear')

In [9]:
trainY.ravel()

array([0, 2, 2, 0, 0, 2, 0, 2, 2, 1, 1, 2, 2, 0, 1, 1, 2, 1, 2, 1, 0, 0,
       0, 2, 0, 1, 2, 2, 0, 0, 1, 0, 2, 1, 2, 2, 1, 2, 2, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 2, 2, 2, 0, 0, 1, 0, 2, 0, 2, 2, 0, 2, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 2, 0, 0, 2, 1, 2, 1, 2, 2, 1,
       2, 0])

In [10]:
def train(classifer, x_train, y_train):
    classifier.fit(x_train, y_train.ravel())

In [11]:
train(classifier, trainX, trainY.ravel())

In [12]:
def calculate_accuracy(groupA, groupB, text):
    accuracy = groupA.ravel() == groupB.ravel()
    print('%s Accuracy: %.4f' %(text, np.mean(accuracy)))

In [13]:
def print_result(x_train, y_train, x_test, y_test, classifier):
    print('Training prediction: %.4f' %(classifier.score(x_train, y_train)))
    print('Testing prediction: %.4f' %(classifier.score(x_test, y_test)))
    calculate_accuracy(classifier.predict(x_train), y_train, 'Training data')
    calculate_accuracy(classifier.predict(x_test), y_test, 'Testing data')
    print('Decision function: \n', classifier.decision_function(x_train))

In [14]:
print_result(trainX, trainY, testX, testY, classifier)

Training prediction: 0.8111
Testing prediction: 0.7833
Training data Accuracy: 0.8111
Testing data Accuracy: 0.7833
Decision function: 
 [[ 2.25461898  0.80414358 -0.2147124 ]
 [-0.23575726  2.22969095  1.0555441 ]
 [-0.26772318  2.22989066  1.21670647]
 [ 2.22861986  0.941209   -0.22106768]
 [ 2.25151409  0.84015975 -0.22760435]
 [-0.26695835  1.20097086  2.23819404]
 [ 2.26619336  0.79348313 -0.2334217 ]
 [-0.23975059  1.17540747  2.19734637]
 [-0.25919758  1.15909453  2.24030592]
 [-0.27260742  1.1955656   2.25142548]
 [-0.20647314  2.18892734  1.080666  ]
 [-0.26617546  1.14960546  2.25299563]
 [-0.22906549  1.1673955   2.1809949 ]
 [ 2.25379984 -0.23321597  0.84571633]
 [-0.27043738  2.25808539  1.15507621]
 [-0.2655801   1.21074165  2.22919143]
 [-0.26695835  1.20097086  2.23819404]
 [ 0.90703755  2.22608556 -0.21084384]
 [-0.23818679  1.09636122  2.22569299]
 [-0.20923801  2.22267836  0.91800013]
 [ 2.21568084 -0.21083237  0.96639039]
 [ 2.225148    0.90226153 -0.20831493]
 [ 2.